#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Illuminate\Contracts\Console\Kernel;

define('LARAVEL_START', microtime(true));

// Charger l'autoloader de Composer
require __DIR__ . '/vendor/autoload.php';

// Charger l'application Laravel
$app = require_once __DIR__ . '/bootstrap/app.php';

// Résoudre l'instance de la console et exécuter la commande
$status = $app->make(Kernel::class)->handle(
    new ArgvInput(),
    new ConsoleOutput()
);

// Quitter avec le statut de la commande
exit($status);
